version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy-aws:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-129-87-17.us-east-2.compute.amazonaws.com "bash -s" < deploy.sh

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - deploy-aws:
          requires:
            - build-and-test
